module.exports = {
    community: [
      {
        type: 'autogenerated',
        dirName: '.',
      },
      {
        type: 'link',
        href: '/youtube',
        label: 'YouTube Channels',
      },
      {
        type: 'link',
        label: 'Chat on Discord',
        href: 'https://discord.gg/czBagVdU',
      }
    ],
  };
  