module.exports = {
    community: [
      {
        type: 'autogenerated',
        dirName: '.',
      },
      {
        type: 'link',
        href: '/links',
        label: 'Usefull Links',
      },
      {
        type: 'link',
        label: 'Chat on Discord',
        href: 'https://discord.gg/czBagVdU',
      }
    ],
  };
  