module.exports = {
    community: [
      {
        type: 'autogenerated',
        dirName: '.',
      },
      // {
      //   type: 'link',
      //   label: 'Follow us on YouTube',
      //   href: 'https://www.youtube.com/channel/UC5i20v6o7lSjXzAHOvatt0w',
      // },
      {
        type: 'link',
        label: 'Chat on Discord',
        href: 'https://discord.gg/czBagVdU',
      },
    ],
  };
  